[build-system]
requires = [
    "setuptools>=71.04",
]

build-backend = "setuptools.build_meta"

[project]
authors = [
    {name = "Rocky Bernstein",	email = "rb@dustyfeet.com"},
]

name = "decompile-cfg"
description = "Python cross-version byte-code library and disassembler"
dependencies = [
    "click",
    "spark-parser >= 1.9.0, < 1.9.2",
    "xdis >= 6.1.2, < 6.1.4",
]
readme = "README.rst"
license = {text = "GPL"}
keywords = ["Python bytecode", "bytecode", "disassembler"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/rocky/python-decompile-cfg"
Downloads = "https://github.com/rocky/python-decompile-cfg/releases"

[project.optional-dependencies]
dev = [
    "pre-commit",
    "pytest",
]

[project.scripts]
decompile_cfg = "decompile_cfg.bin.decompile:main_bin"
decompile_code = "decompile_cfg.bin.decompile_code_type:main"
decompile_tokenize = "decompile_cfg.bin.decompile_cfg_tokens:main"

[tool.setuptools.dynamic]
version = {attr = "decompile_cfg.version.__version__"}
