[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
authors = [
    {name = "Rocky Bernstein",	email = "rb@dustyfeet.com"},
]

name = "decompile-cfg"
description = "Python cross-version byte-code library and disassembler"
dependencies = [
    "click",
    "spark-parser >= 1.8.9, < 1.9.2",
    "xdis >= 6.1.0, < 6.3",
]
readme = "README.rst"
license = "GPL-3.0-or-later"

keywords = ["Python bytecode", "bytecode", "disassembler"]
requires-python = ">=3.8"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/rocky/python-decompile-cfg"
Downloads = "https://github.com/rocky/python-decompile-cfg/releases"

[project.optional-dependencies]
dev = [
    "pre-commit",
    "pytest",
]

[project.scripts]
decompile-cfg = "decompile_cfg.bin.decompile:main_bin"
decompile-code = "decompile_cfg.bin.decompile_code_type:main"
decompile-tokenize = "decompile_cfg.bin.decompile_cfg_tokens:main"

[tool.setuptools.dynamic]
version = {attr = "decompile_cfg.version.__version__"}

[tool.setuptools.packages.find]
include = ["decompyle3*"]  # Include all subpackages
