name: decompile-cfg (ubuntu)

on:
  push:
    branches: [ python-3.6-to-3.10 ]
  pull_request:
    branches: [ python-3.6-to-3.10 ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Until the next xdis release
        pip install git+https://github.com/rocky/python-xdis.git@python-3.6-to-3.10#egg=xdis
        # Until the next control-flow release
        pip install git+https://github.com/rocky/python-control-flow.git#egg=control_flow
        python -m pip install pytest
        pip install -e .[dev]
    - name: Test decompile-cfg
      run: |
        # pytest pytest # for reduced checking
        make check
